import type { Startup } from "./types";

export const SEED_DATA: Startup[] = [
  {
    id: "1",
    companyName: "Closeline",
    slug: "closeline",
    category: "Sales",
    hqLocation: "Austin, TX",
    website: "https://closeline.io",
    yearFounded: 2023,
    fundraisingStage: "Seed",
    employees: "11-50",
    shortDescription: "AI-powered sales pipeline management that helps reps close 40% faster with real-time deal coaching.",
    linkedinUrl: "https://linkedin.com/company/closeline",
    xUrl: "https://x.com/closeline",
    freeTrialUrl: "https://closeline.io/trial",
    news: [
      { id: "n1", title: "Closeline raises $4.2M seed round led by Accel", date: "2026-03-10" },
      { id: "n2", title: "New AI deal scoring feature launches", date: "2026-03-05" },
    ],
    ownerId: "seed",
    createdAt: "2026-03-08",
  },
  {
    id: "2",
    companyName: "MarketMesh",
    slug: "marketmesh",
    category: "Marketing",
    hqLocation: "New York, NY",
    website: "https://marketmesh.co",
    yearFounded: 2024,
    fundraisingStage: "Pre-Seed",
    employees: "1-10",
    shortDescription: "Unified attribution platform connecting every marketing touchpoint to revenue outcomes.",
    newsletterUrl: "https://marketmesh.co/blog",
    linkedinUrl: "https://linkedin.com/company/marketmesh",
    news: [
      { id: "n3", title: "MarketMesh launches multi-touch attribution v2", date: "2026-03-11" },
    ],
    ownerId: "seed",
    createdAt: "2026-03-10",
  },
  {
    id: "3",
    companyName: "LearnLoop",
    slug: "learnloop",
    category: "EdTech",
    hqLocation: "San Francisco, CA",
    website: "https://learnloop.dev",
    yearFounded: 2022,
    fundraisingStage: "Series A",
    employees: "51-200",
    revenue: "$2M ARR",
    shortDescription: "Adaptive learning platform for corporate training that personalizes content using spaced repetition and AI.",
    linkedinUrl: "https://linkedin.com/company/learnloop",
    xUrl: "https://x.com/learnloop",
    youtubeUrl: "https://youtube.com/@learnloop",
    demoUrl: "https://learnloop.dev/demo",
    news: [
      { id: "n4", title: "LearnLoop partners with Fortune 500 for enterprise rollout", date: "2026-03-09" },
      { id: "n5", title: "CEO speaks at SaaStr Annual 2026", date: "2026-02-28" },
    ],
    ownerId: "seed",
    createdAt: "2026-02-15",
  },
  {
    id: "4",
    companyName: "Taskflow",
    slug: "taskflow",
    category: "Project Management",
    hqLocation: "Berlin, Germany",
    website: "https://taskflow.app",
    yearFounded: 2023,
    fundraisingStage: "Bootstrapped",
    employees: "1-10",
    shortDescription: "Opinionated project management for small teams. No bloat, just shipping.",
    xUrl: "https://x.com/taskflowapp",
    newsletterUrl: "https://taskflow.app/changelog",
    news: [
      { id: "n6", title: "Taskflow hits 10,000 active teams", date: "2026-03-12" },
    ],
    ownerId: "seed",
    createdAt: "2026-03-01",
  },
  {
    id: "5",
    companyName: "PingBase",
    slug: "pingbase",
    category: "Communication",
    hqLocation: "London, UK",
    website: "https://pingbase.io",
    yearFounded: 2024,
    fundraisingStage: "Seed",
    employees: "11-50",
    shortDescription: "Async-first team communication with threaded conversations and smart notifications that respect deep work.",
    linkedinUrl: "https://linkedin.com/company/pingbase",
    freeTrialUrl: "https://pingbase.io/start",
    news: [
      { id: "n7", title: "PingBase launches Slack integration", date: "2026-03-07" },
    ],
    ownerId: "seed",
    createdAt: "2026-03-04",
  },
  {
    id: "6",
    companyName: "LedgerAI",
    slug: "ledgerai",
    category: "Finance",
    hqLocation: "Chicago, IL",
    website: "https://ledgerai.com",
    yearFounded: 2022,
    fundraisingStage: "Series B",
    employees: "51-200",
    revenue: "$8M ARR",
    shortDescription: "Automated bookkeeping and financial close for mid-market companies using AI agents.",
    linkedinUrl: "https://linkedin.com/company/ledgerai",
    xUrl: "https://x.com/ledgerai",
    youtubeUrl: "https://youtube.com/@ledgerai",
    news: [
      { id: "n8", title: "LedgerAI closes $22M Series B", date: "2026-03-06" },
      { id: "n9", title: "SOC 2 Type II certification achieved", date: "2026-02-20" },
    ],
    ownerId: "seed",
    createdAt: "2026-01-10",
  },
  {
    id: "7",
    companyName: "HireSignal",
    slug: "hiresignal",
    category: "HR",
    hqLocation: "Toronto, Canada",
    website: "https://hiresignal.co",
    yearFounded: 2023,
    fundraisingStage: "Pre-Seed",
    employees: "1-10",
    shortDescription: "Skills-based hiring platform that replaces resume screening with real-world assessments.",
    xUrl: "https://x.com/hiresignal",
    demoUrl: "https://hiresignal.co/demo",
    news: [
      { id: "n10", title: "HireSignal featured in TechCrunch Startup Battlefield", date: "2026-03-11" },
    ],
    ownerId: "seed",
    createdAt: "2026-03-09",
  },
  {
    id: "8",
    companyName: "DevDock",
    slug: "devdock",
    category: "Developers",
    hqLocation: "Seattle, WA",
    website: "https://devdock.dev",
    yearFounded: 2024,
    fundraisingStage: "Seed",
    employees: "11-50",
    shortDescription: "Developer experience platform that unifies CI/CD, monitoring, and incident response in one dashboard.",
    linkedinUrl: "https://linkedin.com/company/devdock",
    newsletterUrl: "https://devdock.dev/blog",
    news: [
      { id: "n11", title: "DevDock open-sources core monitoring module", date: "2026-03-08" },
    ],
    ownerId: "seed",
    createdAt: "2026-03-06",
  },
  {
    id: "9",
    companyName: "CareStack",
    slug: "carestack",
    category: "Healthcare",
    hqLocation: "Boston, MA",
    website: "https://carestack.health",
    yearFounded: 2021,
    fundraisingStage: "Series A",
    employees: "51-200",
    revenue: "$5M ARR",
    shortDescription: "Patient engagement and care coordination platform for multi-location clinics.",
    linkedinUrl: "https://linkedin.com/company/carestack",
    youtubeUrl: "https://youtube.com/@carestack",
    news: [
      { id: "n12", title: "CareStack expands to 200+ clinic locations", date: "2026-03-03" },
    ],
    ownerId: "seed",
    createdAt: "2026-02-01",
  },
  {
    id: "10",
    companyName: "QueryMind",
    slug: "querymind",
    category: "AI & ML",
    hqLocation: "San Francisco, CA",
    website: "https://querymind.ai",
    yearFounded: 2024,
    fundraisingStage: "Seed",
    employees: "11-50",
    shortDescription: "Natural language interface for databases. Ask questions in English, get SQL and visualizations instantly.",
    xUrl: "https://x.com/querymind",
    freeTrialUrl: "https://querymind.ai/playground",
    news: [
      { id: "n13", title: "QueryMind adds support for 15 database types", date: "2026-03-12" },
      { id: "n14", title: "Named in Y Combinator W26 batch", date: "2026-03-01" },
    ],
    ownerId: "seed",
    createdAt: "2026-03-02",
  },
  {
    id: "11",
    companyName: "ShieldOps",
    slug: "shieldops",
    category: "Cybersecurity",
    hqLocation: "Tel Aviv, Israel",
    website: "https://shieldops.io",
    yearFounded: 2023,
    fundraisingStage: "Series A",
    employees: "51-200",
    shortDescription: "Continuous security posture management for cloud-native companies. Detect misconfigurations before attackers do.",
    linkedinUrl: "https://linkedin.com/company/shieldops",
    news: [
      { id: "n15", title: "ShieldOps detects zero-day in popular npm package", date: "2026-03-10" },
    ],
    ownerId: "seed",
    createdAt: "2026-02-20",
  },
  {
    id: "12",
    companyName: "CartIQ",
    slug: "cartiq",
    category: "E-commerce",
    hqLocation: "Los Angeles, CA",
    website: "https://cartiq.shop",
    yearFounded: 2024,
    fundraisingStage: "Bootstrapped",
    employees: "1-10",
    shortDescription: "AI-powered checkout optimization that recovers abandoned carts and personalizes upsells in real-time.",
    xUrl: "https://x.com/cartiq",
    newsletterUrl: "https://cartiq.shop/insights",
    freeTrialUrl: "https://cartiq.shop/start",
    news: [
      { id: "n16", title: "CartIQ merchants see 28% lift in checkout conversion", date: "2026-03-09" },
    ],
    ownerId: "seed",
    createdAt: "2026-03-07",
  },
];
